version: '3'

services:
  pg:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    volumes:
      - pg-data:/var/lib/postgresql/data/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - '8000:8000'
    env_file:
      - app.env
    depends_on:
      - pg

volumes:
  pg-data: