# Generated by Django 4.0.5 on 2022-06-22 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveSmallIntegerField(default=0, verbose_name='current cell number')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('cell_number', models.PositiveSmallIntegerField(verbose_name='number of cell')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.round')),
            ],
        ),
    ]
