# Generated by Django 4.0.5 on 2022-06-23 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_cell_number_log_cell_remove_round_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='current_attempt',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='current attempt number'),
        ),
    ]
