# Generated by Django 4.0.5 on 2022-06-23 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_round_current_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='round',
            name='current_attempt',
            field=models.PositiveSmallIntegerField(verbose_name='current attempt number'),
        ),
    ]
